"""empty message

Revision ID: 0182e2e1fd29
Revises: 7681580023ad
Create Date: 2025-05-04 14:58:41.430142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0182e2e1fd29'
down_revision = '7681580023ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_captcha')
    # ### end Alembic commands ###
